// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parmezzan.Services.ProductAPI.DbContextes;

#nullable disable

namespace Parmezzan.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220703212244_product_seed_added")]
    partial class product_seed_added
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Parmezzan.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Entree",
                            Description = "Pasta alla carbonara – potrawa kuchni włoskiej złożona z makaronu, jajek, pancetty lub guanciale, sera pecorino romano lub parmezanu oraz czarnego pieprzu. Niepoprawnym jest mówienie o „sosie carbonara”, ponieważ makaron i pozostałe składniki stanowią tu nierozerwalną całość.",
                            ImageUrl = "https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/61FCB2B2-DB84-4A68-ABB8-F9FBA800BCA3/Derivates/FCB48A53-86F0-4697-BE75-7B7CE9B49EBE.jpg",
                            Name = "Spaghetti carbonara",
                            Price = 29.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Entree",
                            Description = "Lasagne, lazania – rodzaj makaronu w postaci dużych, prostokątnych płatów, a także danie przygotowywane na bazie tego makaronu. Makaron jest uprzednio gotowany lub układany na sucho w prostokątnym naczyniu, na przemian z warstwami farszu. Następnie potrawa jest zapiekana.",
                            ImageUrl = "https://d167y3o4ydtmfg.cloudfront.net/357/studio/assets/v1545738807011_736924535/Classico%20Two%20Sauce%20Lasagna-min.jpg",
                            Name = "Lasagna classica",
                            Price = 35.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Dessert",
                            Description = "Panna Cotta oznacza gotowaną śmietankę. Do śmietany dodaje się cukier i często wanilię, a usztywnia żelatyną. Gotowy deser wykłada się do góry dnem na talerz. Żelatyny należy dodać tyle, aby deser trzymam kształt, ale nie był za sztywny.",
                            ImageUrl = "https://bi.im-g.pl/im/45/06/1a/z27290437Q,Panna-Cotta.jpg",
                            Name = "Panna Cotta",
                            Price = 10.99
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Dessert",
                            Description = "Tiramisu – deser złożony z warstwy biszkoptu nasączonej bardzo mocną kawą espresso, na którą nakłada się warstwę kremu z sera mascarpone, żółtek jaj kurzych i cukru, a całość posypuje się warstwą grubo zmielonych płatków gorzkiej czekolady.",
                            ImageUrl = "https://staticsmaker.iplsc.com/smaker_production_2022_01_25/3880ee56bfb96556229f5da649a0a6b4-recipe_main.jpg",
                            Name = "Tiramisu",
                            Price = 10.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
